name: Deploy SWU artifacts to staging bucket

on:
  workflow_dispatch:
    inputs:
      source_path:
        description: "Object key inside"
        required: true
        type: string

jobs:
  deploy-artifacts:
    runs-on: ubuntu-latest
    environment: deploy-test
    steps:
      - name: Copy artifact to staging bucket
        shell: bash
        run: echo "hello"
